
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThZ8U47F3FfuHKPauAXciYjxCyXOW7Qw',
    authDomain: 'salonapp-fcdff.firebaseapp.com',
    projectId: 'salonapp-fcdff',
    storageBucket: 'salonapp-fcdff.appspot.com',
    messagingSenderId: '38251888557',
    appId: '1:38251888557:web:fb675c2cc95f159055ab24',
    measurementId: 'G-CDEJVPB1HQ'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjdmSb42UAG5JsOM7o2QAb3R6fajco8f4',
    appId: '1:38251888557:android:2de399734b72d30955ab24',
    messagingSenderId: '38251888557',
    projectId: 'salonapp-fcdff',
    storageBucket: 'salonapp-fcdff.appspot.com'
  );
}
